import type { Result } from "../api/client";

const months = [
  "2026-08",
  "2026-09",
  "2026-10",
  "2026-11",
  "2026-12",
  "2027-01",
];
const endingCash = [
  95_046_088, 98_142_068, 101_291_743, 104_498_916, 107_767_392, 109_327_299,
];
const trendEndingCash = [
  95_000_000, 98_000_000, 101_000_000, 104_000_000, 107_000_000, 108_226_327,
];
const ingredientSavings = [46_088, 95_980, 149_675, 207_173, 268_475, 333_580];
const cumulativeSavings = [
  46_088, 142_068, 291_743, 498_916, 767_392, 1_100_972,
];

const flow = (
  month: string,
  ending: number,
  ingredientCost = 9_000_000,
  index = 0,
) => ({
  month_index: index + 1,
  month_str: month,
  beginning_cash_krw: ending - 3_000_000,
  revenue_cash_krw: 30_000_000,
  variable_costs_cash_krw: ingredientCost + 3_600_000,
  ingredient_costs_cash_krw: ingredientCost,
  other_variable_costs_cash_krw: 3_600_000,
  fixed_costs_cash_krw: 12_000_000,
  interest_payment_krw: 100_000,
  principal_payment_krw: 500_000,
  tax_cash_outflow_krw: 0,
  capital_expenditure_krw: 0,
  other_cash_inflows_krw: 0,
  net_cash_flow_krw: 3_800_000,
  ending_cash_krw: ending,
});
const scenario = (endingValues: number[], official = false) => ({
  scenario_name: "BASELINE",
  monthly_cash_flows: months.map((month, index) =>
    flow(
      month,
      endingValues[index],
      9_000_000 - (official ? ingredientSavings[index] : 0),
      index,
    ),
  ),
  bep_results: [
    {
      month_index: 1,
      revenue_forecast_krw: 30_000_000,
      variable_cost_ratio: 0.3,
      contribution_margin_ratio: 0.7,
      operating_bep_krw: 20_000_000,
      financial_bep_krw: 20_500_000,
      cash_bep_krw: 21_000_000,
      bep_status: "NORMAL",
      bep_failure_reason: null,
    },
  ],
  cash_burn_result: {
    liquidity_risk_date: null,
    cash_burn_date: null,
    horizon_status: "NO_BURN_WITHIN_HORIZON",
  },
  metadata: { scenario_id: official ? "SCN-OFFICIAL" : "SCN-TREND" },
});

const observationSeries = (
  indicatorId: string,
  sourceId: string,
  revisionId: string,
  unit: string,
  start: number,
  step: number,
) =>
  Array.from({ length: 13 }, (_, index) => {
    const observed = new Date(Date.UTC(2025, 5 + index, 1))
      .toISOString()
      .slice(0, 10);
    return {
      observation_id: `${indicatorId}-OBS-${index}`,
      indicator_id: indicatorId,
      value: start + step * index,
      unit,
      frequency: "MONTHLY",
      observed_at: observed,
      released_at: `${observed}T09:00:00Z`,
      available_at: `${observed}T09:00:00Z`,
      source_id: sourceId,
      source_revision_id: revisionId,
      vintage_id: `VNT-${indicatorId}`,
      normalization_rule_id: "indicator.v1",
      quality_status: "VALID",
    };
  });
const observations = [
  ...observationSeries(
    "BASE_RATE",
    "SRC-ECOS-RATE",
    "REV-ECOS-RATE",
    "PERCENT",
    2.5,
    0,
  ),
  ...observationSeries(
    "USD_KRW",
    "SRC-ECOS-FX",
    "REV-ECOS-FX",
    "KRW_PER_USD",
    1081.21,
    37.19,
  ),
  ...observationSeries(
    "IMPORT_PRICE_INDEX_USD",
    "SRC-ECOS-IPI",
    "REV-ECOS-IPI",
    "INDEX_2020_100",
    232.45,
    -8.99,
  ),
  ...observationSeries(
    "CONSUMER_PRICE_INDEX",
    "SRC-KOSIS-CPI",
    "REV-KOSIS-CPI",
    "INDEX_2020_100",
    119.15,
    0.07,
  ),
];
const metadata = (
  indicator_id: string,
  display_name: string,
  provider: string,
  provider_series_code: string,
  feature_role: string,
  unit: string,
  max_age_days: number,
) => ({
  indicator_id,
  display_name,
  provider,
  provider_series_code,
  feature_role,
  unit,
  frequency: "MONTHLY",
  max_age_days,
  transformation_method: "RECENT_CHANGE_LINEAR_PROJECTION",
  affected_model_dimension:
    feature_role === "INTEREST_RATE" ? "INTEREST_PAYMENT" : feature_role,
  description: null,
});
const collection = (
  indicator_id: string,
  display_name: string,
  provider: string,
  series: string,
  role: string,
  unit: string,
  previous: number,
  latest: number,
  maxAge: number,
) => ({
  provider,
  indicator_id,
  requested: true,
  required: false,
  status: "COMPLETED",
  observation_count: 13,
  latest_observation_id: `${indicator_id}-OBS-12`,
  previous_observation_id: `${indicator_id}-OBS-11`,
  latest_value: latest,
  previous_value: previous,
  unit,
  absolute_change: latest - previous,
  percentage_change: (latest - previous) / Math.abs(previous),
  latest_observed_at: "2026-06-01",
  latest_released_at: "2026-06-20T09:00:00Z",
  latest_available_at: "2026-06-20T09:00:00Z",
  freshness_age_days: 58,
  freshness_max_age_days: maxAge,
  freshness_status: "VALID",
  metadata: metadata(
    indicator_id,
    display_name,
    provider,
    series,
    role,
    unit,
    maxAge,
  ),
});
const projected = [
  ["2026-08", 2.5, 120.06, 115.59, 1564.49, 1, 0.986079, 1.000584, 0.978826],
  ["2026-09", 2.5, 120.13, 106.6, 1601.68, 1, 0.972157, 1.001167, 0.957652],
  ["2026-10", 2.5, 120.2, 97.61, 1638.87, 1, 0.958236, 1.001751, 0.936479],
  ["2026-11", 2.5, 120.27, 88.62, 1676.06, 1, 0.944315, 1.002335, 0.915305],
  ["2026-12", 2.5, 120.34, 79.63, 1713.25, 1, 0.930393, 1.002919, 0.894131],
  ["2027-01", 2.5, 120.41, 70.64, 1750.44, 1, 0.916472, 1.003502, 0.872957],
] as const;

export const completedResult = {
  schema_version: "analysis_result.v1",
  result_id: "AR-RUN-7FABA7E0-B71-V1",
  result_version: 1,
  run_id: "RUN-7FABA7E0-B71",
  tenant_id: "default",
  idempotency_key: "diagnostic-fixture",
  status: "PARTIAL",
  created_at: "2026-07-29T10:00:00Z",
  completed_at: "2026-07-29T10:02:00Z",
  as_of_date: "2026-07-29",
  forecast_start: "2026-08-01",
  forecast_end: "2027-01-31",
  deterministic_hash: "diagnostic-fixture-hash",
  input_snapshot: {
    store_profile: {
      store_id: "DEMO-CAFE-2026",
      address: "Seoul Gangnam-gu Teheran-ro 152",
      current_cash_krw: 92_000_000,
    },
    research_request: { as_of_date: "2026-07-29" },
    official_requests: [],
  },
  sections: {
    INPUT: { status: "COMPLETED" },
    OFFICIAL_DATA: { status: "PARTIAL" },
    BASELINE: { status: "COMPLETED" },
    RESEARCH: { status: "COMPLETED" },
    SIGNALS: { status: "COMPLETED" },
    FINANCE: { status: "COMPLETED" },
    POLICIES: { status: "PARTIAL" },
    RESULT_ASSEMBLY: { status: "COMPLETED" },
  },
  section_status_summary: [
    {
      section: "OFFICIAL_DATA",
      label: "Official data",
      status: "PARTIAL",
      record_count: 52,
      warnings: ["NO_OBSERVATIONS"],
      failure_codes: [],
      effect:
        "Four indicators were applied; optional Customs coffee data was unavailable.",
    },
    {
      section: "RESEARCH",
      label: "Risk research",
      status: "COMPLETED",
      record_count: 0,
      warnings: [],
      failure_codes: [],
      effect: "Risk agents completed; no candidate passed validation.",
    },
    {
      section: "SIGNALS",
      label: "Signals",
      status: "COMPLETED",
      record_count: 0,
      warnings: [],
      failure_codes: [],
      effect: "No validated, eligible event adjusted finance.",
    },
    {
      section: "FINANCE",
      label: "Finance",
      status: "COMPLETED",
      record_count: 4,
      warnings: [],
      failure_codes: [],
      effect:
        "Trend, official, low-impact, and high-impact scenarios were calculated.",
    },
    {
      section: "POLICIES",
      label: "Policies",
      status: "PARTIAL",
      record_count: 0,
      warnings: ["OpenAI /v1/responses returned HTTP 400"],
      failure_codes: [],
      effect:
        "Policy candidates are unavailable; risk-research status is unaffected.",
    },
  ],
  official_data: {
    snapshot_id: "ODS-DIAGNOSTIC",
    as_of_date: "2026-07-29",
    status: "PARTIAL",
    observations,
    source_vintages: [
      {
        vintage_id: "VNT-BASE_RATE",
        provider: "ECOS",
        source_id: "SRC-ECOS-RATE",
        source_revision_id: "REV-ECOS-RATE",
        revision_basis: "CONTENT_HASH",
        retrieved_at: "2026-07-29T09:00:00Z",
        body_hash: "a".repeat(64),
        observation_count: 13,
        raw_payload: [],
      },
      {
        vintage_id: "VNT-USD_KRW",
        provider: "ECOS",
        source_id: "SRC-ECOS-FX",
        source_revision_id: "REV-ECOS-FX",
        revision_basis: "CONTENT_HASH",
        retrieved_at: "2026-07-29T09:00:00Z",
        body_hash: "b".repeat(64),
        observation_count: 13,
        raw_payload: [],
      },
    ],
    frequency_transforms: [],
    freshness: [],
    collection_results: [
      collection(
        "BASE_RATE",
        "Bank of Korea base rate",
        "ECOS",
        "722Y001:0101000",
        "INTEREST_RATE",
        "PERCENT",
        2.5,
        2.5,
        90,
      ),
      collection(
        "USD_KRW",
        "USD/KRW monthly average exchange rate",
        "ECOS",
        "731Y004:0000001:0000100",
        "IMPORTED_INGREDIENT_COST",
        "KRW_PER_USD",
        1490.11,
        1527.3,
        90,
      ),
      collection(
        "IMPORT_PRICE_INDEX_USD",
        "Import price index (USD basis)",
        "ECOS",
        "401Y015:*AA:D",
        "IMPORTED_INGREDIENT_COST",
        "INDEX_2020_100",
        133.57,
        124.58,
        120,
      ),
      collection(
        "CONSUMER_PRICE_INDEX",
        "Consumer price index",
        "KOSIS",
        "101:DT_1J22003:T:NATIONAL",
        "DOMESTIC_INGREDIENT_COST",
        "INDEX_2020_100",
        119.92,
        119.99,
        120,
      ),
      {
        provider: "CUSTOMS",
        indicator_id: "CUSTOMS_IMPORT_UNIT_PRICE_USD_PER_KG_HS0901110000",
        requested: true,
        required: false,
        status: "MISSING",
        observation_count: 0,
        latest_observation_id: null,
        previous_observation_id: null,
        freshness_status: "MISSING",
        failure_code: "NO_OBSERVATIONS",
        failure_detail: "CUSTOMS: NO_OBSERVATIONS",
        missing_data_behavior:
          "The model continued without this optional indicator.",
        metadata: metadata(
          "CUSTOMS_IMPORT_UNIT_PRICE_USD_PER_KG_HS0901110000",
          "Coffee import unit price (green beans)",
          "CUSTOMS",
          "ITEMTRADE:090111",
          "IMPORTED_INGREDIENT_COST",
          "USD_PER_KG",
          120,
        ),
      },
    ],
    missing_indicators: ["CUSTOMS_IMPORT_UNIT_PRICE_USD_PER_KG_HS0901110000"],
    provider_errors: { CUSTOMS: "NO_OBSERVATIONS" },
    version: "official_data_bundle.v1",
  },
  official_features: {
    feature_set_id: "OFS-DIAGNOSTIC",
    as_of_date: "2026-07-29",
    indicator_ids: [
      "BASE_RATE",
      "CONSUMER_PRICE_INDEX",
      "IMPORT_PRICE_INDEX_USD",
      "USD_KRW",
    ],
    source_snapshot_id: "ODS-DIAGNOSTIC",
    status: "COMPLETED",
    transformation_version: "official_features.v1",
    assumptions: [
      "Feature projections are deterministic scenario inputs, not official forecasts",
    ],
    months: projected.map(
      (
        [month, rate, cpi, ipi, fx, revenue, combined, domestic, imported],
        index,
      ) => ({
        month,
        revenue_index_multiplier: revenue,
        ingredient_cost_multiplier: combined,
        domestic_ingredient_cost_multiplier: domestic,
        imported_ingredient_cost_multiplier: imported,
        interest_rate_delta: 0,
        indicator_values: {
          BASE_RATE: rate,
          CONSUMER_PRICE_INDEX: cpi,
          IMPORT_PRICE_INDEX_USD: ipi,
          USD_KRW: fx,
        },
        source_observation_ids: [
          "BASE_RATE-OBS-12",
          "CONSUMER_PRICE_INDEX-OBS-12",
          "IMPORT_PRICE_INDEX_USD-OBS-12",
          "USD_KRW-OBS-12",
        ],
        assumptions: ["Projected model input; not an official agency forecast"],
        contributions: [
          {
            month,
            indicator_id: "USD_KRW",
            provider: "ECOS",
            feature_role: "IMPORTED_INGREDIENT_COST",
            affected_model_dimension: "IMPORTED_INGREDIENT_COST",
            latest_observation_id: "USD_KRW-OBS-12",
            previous_observation_id: "USD_KRW-OBS-11",
            latest_value: 1527.3,
            previous_value: 1490.11,
            unit: "KRW_PER_USD",
            latest_observed_at: "2026-06-01",
            latest_released_at: "2026-06-20T09:00:00Z",
            absolute_change: 37.19,
            relative_change: 0.024958,
            capped_relative_change: 0.024958,
            projection_step: index + 1,
            projected_value: fx,
            contributed_multiplier_delta: 0.012479 * (index + 1),
            assumptions: [
              "Projected model input; not an official agency forecast",
            ],
            source_observation_ids: ["USD_KRW-OBS-11", "USD_KRW-OBS-12"],
          },
          {
            month,
            indicator_id: "IMPORT_PRICE_INDEX_USD",
            provider: "ECOS",
            feature_role: "IMPORTED_INGREDIENT_COST",
            affected_model_dimension: "IMPORTED_INGREDIENT_COST",
            latest_observation_id: "IMPORT_PRICE_INDEX_USD-OBS-12",
            previous_observation_id: "IMPORT_PRICE_INDEX_USD-OBS-11",
            latest_value: 124.58,
            previous_value: 133.57,
            unit: "INDEX_2020_100",
            latest_observed_at: "2026-06-01",
            latest_released_at: "2026-06-20T09:00:00Z",
            absolute_change: -8.99,
            relative_change: -0.067306,
            capped_relative_change: -0.067306,
            projection_step: index + 1,
            projected_value: ipi,
            contributed_multiplier_delta: -0.033653 * (index + 1),
            assumptions: [
              "Projected model input; not an official agency forecast",
            ],
            source_observation_ids: [
              "IMPORT_PRICE_INDEX_USD-OBS-11",
              "IMPORT_PRICE_INDEX_USD-OBS-12",
            ],
          },
        ],
      }),
    ),
  },
  trend_baseline: {
    selected_model: "RECENT_TREND",
    monthly_forecasts: months.map((month) => ({ month, point: 30_000_000 })),
  },
  trend_scenario: scenario(trendEndingCash),
  baseline: {
    selected_model: "RECENT_TREND",
    monthly_forecasts: months.map((month) => ({ month, point: 30_000_000 })),
  },
  scenarios: {
    BASELINE: scenario(endingCash, true),
    LOW_IMPACT: scenario(endingCash, true),
    HIGH_IMPACT: scenario(endingCash, true),
  },
  forecast_layer_comparisons: [
    {
      comparison_id: "CMP-TREND-OFFICIAL",
      base_layer: "TREND",
      comparison_layer: "OFFICIAL",
      attribution_scope: "FEATURE_GROUP",
      ending_cash_delta_krw: 1_100_972,
      source_feature_set_id: "OFS-DIAGNOSTIC",
      event_ids: [],
      signal_ids: [],
      base_scenario_id: "SCN-TREND",
      comparison_scenario_id: "SCN-OFFICIAL",
      attribution: [
        {
          component: "REVENUE",
          label: "Revenue adjustment",
          signed_cash_effect_krw: 0,
        },
        {
          component: "INGREDIENT_COST",
          label: "Ingredient cost adjustment",
          signed_cash_effect_krw: 1_100_972,
        },
        {
          component: "INTEREST",
          label: "Interest adjustment",
          signed_cash_effect_krw: 0,
        },
      ],
      monthly_deltas: months.map((month, index) => ({
        month,
        base_revenue_cash_krw: 30_000_000,
        comparison_revenue_cash_krw: 30_000_000,
        revenue_cash_delta_krw: 0,
        base_ingredient_cost_krw: 9_000_000,
        comparison_ingredient_cost_krw: 9_000_000 - ingredientSavings[index],
        ingredient_cost_delta_krw: -ingredientSavings[index],
        ingredient_cost_savings_krw: ingredientSavings[index],
        base_interest_payment_krw: 100_000,
        comparison_interest_payment_krw: 100_000,
        interest_payment_delta_krw: 0,
        base_net_cash_flow_krw: 3_800_000,
        comparison_net_cash_flow_krw: 3_800_000 + ingredientSavings[index],
        net_cash_flow_delta_krw: ingredientSavings[index],
        base_ending_cash_krw: trendEndingCash[index],
        comparison_ending_cash_krw: endingCash[index],
        ending_cash_delta_krw: cumulativeSavings[index],
      })),
    },
    {
      comparison_id: "CMP-OFFICIAL-AI-HIGH_IMPACT",
      base_layer: "OFFICIAL",
      comparison_layer: "AI_HIGH_IMPACT",
      attribution_scope: "FEATURE_GROUP",
      ending_cash_delta_krw: 0,
      attribution: [],
      monthly_deltas: [],
      event_ids: [],
      signal_ids: [],
    },
  ],
  research: {
    version: "research_result_summary.v1",
    bundles: [],
    accepted_events: [],
    rejected_events: [
      {
        candidate_id: "EC-001",
        status: "RETRYABLE",
        failure_codes: ["DATE_PARSE_FAILED"],
        failure_details: [
          {
            code: "DATE_PARSE_FAILED",
            message:
              "The candidate date could not be normalized deterministically.",
            retryable: true,
          },
        ],
        domain: "INDUSTRY",
        event_family: "INGREDIENT_SUPPLY",
        event_type: "WHOLESALE_PRICE_INCREASE",
        title: "Cocoa international price increase",
        actor_org_raw: "Ministry of Agriculture, Food and Rural Affairs",
        target_subject_raw: "Cocoa",
        temporal: { start_raw: "25.1.16", end_raw: null },
        location: {},
        affected_industries_raw: ["FNB_CAFE"],
        impacts: [
          {
            axis: "INGREDIENT_COST",
            direction: "INCREASE",
            mechanism: "WHOLESALE_PRICE_CHANGE",
            evidence_ids: ["EVD-001"],
          },
        ],
        evidence: [
          {
            evidence_id: "EVD-001",
            source_id: "SRC-5E655BDA58589D936D69",
            source_revision_id: "REV-0AD6AD422D4FA50941A3",
            field_paths: ["event_type", "temporal.start_raw", "impacts[0]"],
            quote:
              "Cocoa international prices increased as of January 16, 2025.",
            start_offset: 120,
            end_offset: 185,
          },
        ],
        source_ids: ["SRC-5E655BDA58589D936D69"],
        source_revision_ids: ["REV-0AD6AD422D4FA50941A3"],
        signal_enabled: false,
        signal_eligibility_reason:
          "Wholesale price levels are represented by official price indicators when available; this event type is kept as research evidence to avoid double-counting the same price movement.",
        retry: {
          attempted: true,
          outcome: "RETRYABLE",
          candidate_id: "EC-001",
        },
      },
    ],
    errors: ["POLICY_REGULATION: OpenAI /v1/responses returned HTTP 400"],
    risk_status: "COMPLETED",
    policy_status: "PARTIAL",
    funnel: {
      query_count: 18,
      document_count: 25,
      access_failure_count: 4,
      candidate_count: 1,
      accepted_event_count: 0,
      signal_eligible_event_count: 0,
      applied_signal_count: 0,
    },
    agent_summaries: [
      {
        agent_type: "MACRO",
        category: "RISK_RESEARCH",
        status: "COMPLETED",
        query_count: 4,
        document_count: 5,
        candidate_count: 0,
        access_failure_count: 3,
        model_call_count: 4,
        no_result_reasons: ["NO_VALID_EVENT_CANDIDATES"],
        providers: ["Gemini"],
        models: ["gemini-search"],
        total_latency_ms: 4100,
        input_tokens: 1200,
        output_tokens: 500,
      },
      {
        agent_type: "INDUSTRY",
        category: "RISK_RESEARCH",
        status: "COMPLETED",
        query_count: 6,
        document_count: 9,
        candidate_count: 1,
        access_failure_count: 1,
        model_call_count: 7,
        no_result_reasons: [],
        providers: ["Gemini", "OpenAI"],
        models: ["gemini-search", "gpt-extraction"],
        total_latency_ms: 6200,
        input_tokens: 2400,
        output_tokens: 900,
      },
      {
        agent_type: "LOCAL_EVENT",
        category: "RISK_RESEARCH",
        status: "COMPLETED",
        query_count: 8,
        document_count: 11,
        candidate_count: 0,
        access_failure_count: 0,
        model_call_count: 8,
        no_result_reasons: ["NO_VALID_EVENT_CANDIDATES"],
        providers: ["Gemini"],
        models: ["gemini-search"],
        total_latency_ms: 5300,
        input_tokens: 1900,
        output_tokens: 600,
      },
      {
        agent_type: "POLICY_REGULATION",
        category: "POLICY",
        status: "PARTIAL",
        query_count: 0,
        document_count: 0,
        candidate_count: 0,
        access_failure_count: 0,
        model_call_count: 1,
        no_result_reasons: ["PROVIDER_HTTP_400"],
        providers: ["OpenAI"],
        models: ["gpt-policy"],
        total_latency_ms: 800,
        input_tokens: 300,
        output_tokens: 0,
      },
    ],
    no_signal_explanation: {
      headline: "No financial AI signals were applied.",
      reason_codes: [
        "NO_VALIDATED_SIGNAL_ELIGIBLE_EVENT",
        "DATE_PARSE_FAILED",
        "SIGNAL_DISABLED_EVENT_TYPE",
        "SOURCE_ACCESS_FAILURES",
      ],
      facts: [
        "18 searches produced 25 documents and 1 candidate.",
        "The candidate failed date normalization (DATE_PARSE_FAILED).",
        "WHOLESALE_PRICE_INCREASE is signal-disabled to avoid double-counting official price data.",
        "4 source documents could not be accessed.",
      ],
      limitation:
        "No applied signal does not mean that no real-world risk exists; it means no validated, eligible signal was available to this run.",
    },
  },
  signals: [],
  adjustments: {},
  policies: {
    search_context: {
      business_type_code: "FNB_CAFE",
      region_codes: ["11680"],
      purposes: ["WORKING_CAPITAL"],
    },
    candidates: [
      {
        policy_candidate_id: "POL-1",
        name: "Small business operating fund",
        provider_raw: "Synthetic policy agency",
        policy_type: "LOAN",
        limit_krw: 50_000_000,
        budget_status: "UNKNOWN",
        validation_status: "REFERENCE_ONLY",
      },
    ],
    validation_results: [],
    eligibility_results: [
      {
        policy_id: "POL-1",
        status: "NEEDS_INFORMATION",
        reason: "Additional sales evidence is required",
        source_ids: [],
      },
    ],
    benefit_simulations: [],
    ranked_options: [],
    official_confirmation_required: true,
    version: "policy_result_bundle.v1",
  },
  traceability: {
    source_ids: [
      "SRC-5E655BDA58589D936D69",
      "SRC-ECOS-RATE",
      "SRC-ECOS-FX",
      "SRC-ECOS-IPI",
      "SRC-KOSIS-CPI",
    ],
    source_revision_ids: [
      "REV-0AD6AD422D4FA50941A3",
      "REV-ECOS-RATE",
      "REV-ECOS-FX",
      "REV-ECOS-IPI",
      "REV-KOSIS-CPI",
    ],
    official_snapshot_ids: ["ODS-DIAGNOSTIC"],
    official_observation_ids: observations.map((item) => item.observation_id),
    event_ids: [],
    signal_ids: [],
    policy_ids: ["POL-1"],
    model_run_ids: ["FC-TREND", "FC-OFFICIAL"],
    scenario_ids: ["SCN-TREND", "SCN-OFFICIAL"],
    calculation_result_ids: ["SCN-TREND", "SCN-OFFICIAL"],
  },
  versions: {
    analysis_result_schema_version: "analysis_result.v1",
    event_registry_version: "event_types.v1",
    coefficient_version: "coefficients.v1",
    official_feature_version: "official_features.v1",
    financial_calculation_version: "financial_calculation.v2",
  },
  warnings: [],
  limitations: [
    "Forecast intervals and policy effects are decision-support estimates, not guarantees.",
  ],
} as unknown as Result;

export const partialResult = {
  ...completedResult,
  status: "PARTIAL",
  warnings: [
    "Policy research is partial; risk research and financial calculations remain available.",
  ],
} as Result;

const replayEvidence = {
  evidence_id: "EVD-RECORDED-SEOUL-ACCESS-1",
  source_id: "SRC-RECORDED-SEOUL-ACCESS",
  source_revision_id: "REV-RECORDED-SEOUL-ACCESS-1",
  field_paths: ["event_type", "start_date", "end_date", "impacts[0]"],
  quote:
    "Seoul City announced a partial pedestrian-path closure near the recorded Gangnam cafe from 2026-08-01 through 2026-09-15.",
  start_offset: 0,
  end_offset: 137,
};

const replayEvent = {
  event_id: "EVT-RECORDED-SEOUL-ACCESS-1",
  candidate_ids: ["EVC-RECORDED-SEOUL-ACCESS-1"],
  research_run_id: "ABC-C-REPLAY",
  domain: "LOCAL",
  event_family: "ACCESSIBILITY",
  event_type: "PEDESTRIAN_PARTIAL_CLOSURE",
  title: "강남 카페 인근 보행로 일부 통제",
  actor_org_raw: "Seoul City",
  target_subject_raw: "Recorded Gangnam cafe access",
  start_date: "2026-08-01",
  end_date: "2026-09-15",
  location: {
    text_raw: "Recorded Gangnam cafe",
    normalized_address: "서울특별시 강남구 테헤란로 152",
    latitude: 37.5007,
    longitude: 127.0365,
    geocode_status: "SUCCESS",
  },
  affected_industry_codes: ["FNB_CAFE"],
  impacts: [
    {
      axis: "REVENUE_DEMAND",
      direction: "DECREASE",
      mechanism: "PEDESTRIAN_ACCESS_RESTRICTION",
      evidence_ids: [replayEvidence.evidence_id],
    },
  ],
  attributes: { closure_scope: "PARTIAL" },
  evidence: [replayEvidence],
  source_ids: [replayEvidence.source_id],
  source_revision_ids: [replayEvidence.source_revision_id],
  source_tier: "OFFICIAL_LOCAL_GOV",
  validation_status: "ACCEPTED",
  validation_failure_codes: [],
  normalization_records: [
    {
      field_path: "start_date",
      raw_value: "2026-08-01",
      normalized_value: "2026-08-01",
      rule_id: "iso_date",
      rule_version: "v1",
    },
  ],
  fingerprint: "recorded-seoul-access-20260801",
  cause_group_id: "CG-RECORDED-ACCESS",
  signal_enabled: true,
  signal_eligibility_reason: "접근성 저하 이벤트는 매출 수요 조정 대상입니다.",
  schema_version: "canonical_event.v1",
  registry_version: "event_types.v1",
};

const replayScenario = (
  endingValues: number[],
  scenarioName: "LOW_IMPACT" | "HIGH_IMPACT",
  scenarioId: string,
) => ({
  ...scenario(endingValues, true),
  scenario_name: scenarioName,
  metadata: { scenario_id: scenarioId },
});

const replayPolicy = {
  policy_candidate_id: "POL-GANGNAM-INTEREST-2026",
  research_run_id: "ABC-C-REPLAY",
  policy_type: "INTEREST_SUBSIDY",
  name: "2026년 강남구 중소기업·소상공인 대출이자 지원사업",
  provider_raw: "강남구청",
  purpose: ["WORKING_CAPITAL"],
  region_codes: ["11680"],
  industry_inclusions_raw: [],
  industry_exclusions_raw: [],
  limit_krw: 50_000_000,
  interest_terms: { rate_discount_percentage_points: 2 },
  guarantee_terms: {},
  repayment_terms: {},
  application_start: null,
  application_end: null,
  budget_status: "UNKNOWN",
  eligibility_conditions: [],
  source_ids: ["SRC-GANGNAM-POLICY-2026"],
  evidence: [
    {
      evidence_id: "EVD-GANGNAM-POLICY-TITLE",
      source_id: "SRC-GANGNAM-POLICY-2026",
      source_revision_id: "REV-GANGNAM-POLICY-2026-1",
      field_paths: ["name", "provider_raw"],
      quote: "2026년 강남구 중소기업·소상공인 대출이자 지원사업 안내",
      start_offset: 0,
      end_offset: 35,
    },
  ],
  notice_kind: "ORIGINAL",
  validation_status: "REFERENCE_ONLY",
  schema_version: "policy_candidate.v1",
};

export const evidenceReplayResult = {
  ...completedResult,
  result_id: "AR-ABC-C-REPLAY-V1",
  run_id: "ABC-C-REPLAY",
  idempotency_key: "recorded-evidence-replay",
  status: "COMPLETED",
  deterministic_hash: "recorded-evidence-replay-hash",
  evidence_replay: {
    mode: "RECORDED_EVIDENCE_REPLAY",
    fixture_id: "controlled_abc_replay.v1",
    captured_from: "SANITIZED_DETERMINISTIC_FALLBACK",
    source_urls: [
      "https://www.seoul.go.kr/recorded-contract-not-live",
      "https://www.gangnam.go.kr/board/B_000001/1076295/view.do?mid=ID05_040101",
    ],
    notice:
      "검증 가능한 계약과 출처 URL을 고정한 재현 데모입니다. 현재 시점의 실시간 검색 결과가 아닙니다.",
  },
  research: {
    ...completedResult.research,
    accepted_events: [replayEvent],
    reference_findings: [
      {
        finding_id: "FND-GANGNAM-POLICY-REFERENCE",
        research_run_id: "ABC-C-REPLAY",
        agent_type: "POLICY_REGULATION",
        domain: "POLICY",
        title: "강남구 대출이자 지원사업 관련 공고",
        relevance_summary:
          "공식 공고 제목을 확인했지만, 이 참고 발견 자체는 매출·비용·현금흐름을 변경하지 않습니다.",
        source_ids: ["SRC-GANGNAM-POLICY-2026"],
        source_revision_ids: ["REV-GANGNAM-POLICY-2026-1"],
        evidence: replayPolicy.evidence,
        missing_requirements: ["STRICT_EVENT_TEMPORAL_AND_IMPACT_EVIDENCE"],
        status: "REFERENCE_ONLY",
        reason_code: "REFERENCE_FINDINGS_ONLY",
        recommended_follow_up: "REVIEW_OFFICIAL_NOTICE",
        financial_signal_eligible: false,
      },
    ],
    errors: [],
    risk_status: "COMPLETED",
    policy_status: "COMPLETED",
    funnel: {
      query_count: 18,
      discovery_hit_count: 31,
      document_count: 25,
      resolved_source_count: 21,
      usable_document_count: 12,
      access_failure_count: 4,
      navigation_only_count: 3,
      duplicate_document_count: 2,
      reference_finding_count: 1,
      candidate_count: 2,
      rejected_candidate_count: 1,
      accepted_event_count: 1,
      signal_eligible_event_count: 1,
      applied_signal_count: 1,
      provider_failure_count: 0,
    },
    no_signal_explanation: null,
  },
  signals: [
    {
      signal_id: "SIG-RECORDED-ACCESS-2026-08",
      event_id: replayEvent.event_id,
      source_ids: replayEvent.source_ids,
      store_id: "DEMO-CAFE-2026",
      month: "2026-08",
      impact_axis: "REVENUE_DEMAND",
      direction: -1,
      evidence_score: "0.92",
      exposure_score: "0.78",
      severity_score: "0.45",
      time_decay: "1.00",
      raw_signal: "-0.032292",
      coefficient_id: "COEF-PEDESTRIAN-PARTIAL-CLOSURE",
      coefficient_status: "ACTIVE",
      cause_group_id: "CG-RECORDED-ACCESS",
      calculation_version: "store_signal.v1",
    },
  ],
  scenarios: {
    ...completedResult.scenarios,
    LOW_IMPACT: replayScenario(
      [
        94_846_088, 97_742_068, 100_691_743, 103_698_916, 106_767_392,
        108_127_299,
      ],
      "LOW_IMPACT",
      "SCN-AI-LOW_IMPACT-REPLAY",
    ),
    HIGH_IMPACT: replayScenario(
      [
        94_646_088, 97_342_068, 100_091_743, 102_898_916, 105_767_392,
        106_927_299,
      ],
      "HIGH_IMPACT",
      "SCN-AI-HIGH_IMPACT-REPLAY",
    ),
  },
  forecast_layer_comparisons: [
    ...(completedResult.forecast_layer_comparisons ?? []).slice(0, 1),
    {
      comparison_id: "CMP-OFFICIAL-AI-HIGH_IMPACT-REPLAY",
      base_layer: "OFFICIAL",
      comparison_layer: "AI_HIGH_IMPACT",
      attribution_scope: "EVENT_SIGNAL",
      ending_cash_delta_krw: -2_400_000,
      attribution: [
        {
          component: "REVENUE",
          label: "보행 접근 제한 매출 조정",
          signed_cash_effect_krw: -2_400_000,
        },
      ],
      monthly_deltas: [],
      event_ids: [replayEvent.event_id],
      signal_ids: ["SIG-RECORDED-ACCESS-2026-08"],
      base_scenario_id: "SCN-OFFICIAL",
      comparison_scenario_id: "SCN-AI-HIGH_IMPACT-REPLAY",
    },
  ],
  policies: {
    ...completedResult.policies,
    candidates: [replayPolicy],
    eligibility_results: [
      {
        policy_id: replayPolicy.policy_candidate_id,
        status: "NEEDS_INFORMATION",
        reason:
          "공식 공고 원문에서 현재 접수 상태와 업체별 자격을 다시 확인해야 합니다.",
        source_ids: replayPolicy.source_ids,
      },
    ],
  },
  traceability: {
    ...completedResult.traceability,
    source_ids: [
      ...(completedResult.traceability.source_ids ?? []),
      replayEvidence.source_id,
      "SRC-GANGNAM-POLICY-2026",
    ],
    source_revision_ids: [
      ...(completedResult.traceability.source_revision_ids ?? []),
      replayEvidence.source_revision_id,
      "REV-GANGNAM-POLICY-2026-1",
    ],
    event_ids: [replayEvent.event_id],
    signal_ids: ["SIG-RECORDED-ACCESS-2026-08"],
    policy_ids: [replayPolicy.policy_candidate_id],
    scenario_ids: [
      "SCN-TREND",
      "SCN-OFFICIAL",
      "SCN-AI-LOW_IMPACT-REPLAY",
      "SCN-AI-HIGH_IMPACT-REPLAY",
    ],
  },
  versions: {
    ...completedResult.versions,
    official_feature_version: "official_features.v2.decayed_capped",
  },
  warnings: [
    "이 결과는 고정된 재현 fixture이며 현재 시점의 실시간 공급자 응답이 아닙니다.",
  ],
} as unknown as Result;

export const noEventResult = {
  ...completedResult,
  result_id: "AR-NO-EVENT-V1",
  run_id: "RUN-NO-EVENT",
  status: "COMPLETED",
  research: {
    ...completedResult.research,
    accepted_events: [],
    rejected_events: [],
    reference_findings: [],
    errors: [],
    funnel: {
      query_count: 8,
      discovery_hit_count: 14,
      document_count: 10,
      resolved_source_count: 10,
      usable_document_count: 7,
      access_failure_count: 0,
      navigation_only_count: 0,
      duplicate_document_count: 1,
      reference_finding_count: 0,
      candidate_count: 0,
      rejected_candidate_count: 0,
      accepted_event_count: 0,
      signal_eligible_event_count: 0,
      applied_signal_count: 0,
      provider_failure_count: 0,
    },
    no_signal_explanation: {
      headline: "예측 기간의 개별 이벤트를 찾지 못했습니다.",
      reason_codes: ["NO_DISCRETE_EVENT"],
      facts: ["사용 가능한 상세 문서 7건을 검토했습니다."],
      limitation:
        "신호 없음은 위험 없음이 아니라, 엄격한 적용 근거가 없었다는 뜻입니다.",
    },
  },
  signals: [],
} as unknown as Result;
